<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="Forms\FrmMain.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FrmCustomers.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FrmProducts.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FrmInvoiceModal.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
      <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\wBusinessLogicLayer\wBusinessLogicLayer.csproj" />
    </ItemGroup>

</Project>